### ISSUE TITLE
Ping to clang-libcxx

### ISSUE THREAD

**Issue by mu578** [mclow/string_view#1]
Hello Marshall,
as there is no way to submit entries on GitHub mirror for clang-libcxx? should think about embracing fully and plainly this age; exim mailing-list beurk; hence, I ping you there; sorry for the inconvenience:

[cmath_beta.tcc.txt](https://github.com/mclow/string_view/files/3259109/cmath_beta.tcc.txt)

You have a good day.

**Comment by mclow** [comment]
The place to submit bug reports for libc++ (and the rest of LLVM) is https://bugs.llvm.org
